version: "3"
services:
  redis:
    image: redis:7.2.1
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  api:
    image: simple-socket-chat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/var/www/app/index.js
    depends_on:
      - redis
    ports:
      - 3000:3000
    command: ['dev']
volumes:
  redisdata: ~
