version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  api:
    image: simple-socket-chat
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "sleep 1; exec node_modules/.bin/nodemon -L index.js"
    depends_on:
      - redis
    ports:
      - 3000:3000
volumes:
  redisdata: ~
